apiVersion: v1
kind: Secret
metadata:
  name: dify-plus-secrets
  namespace: dify-plus
type: Opaque
data:
  # Base64 encoded secrets - Replace with actual base64 encoded values
  # Use: echo -n 'your-secret' | base64
  SECRET_KEY: c2stOWY3M3MzbGpUWFZjTVQzQmxiM2xqVHF0c0tpR0hYVmNNTDNCbGJrRkpMSzdV
  INIT_PASSWORD: ""
  DB_PASSWORD: ZGlmeWFpMTIzNDU2
  REDIS_PASSWORD: ZGlmeWFpMTIzNDU2
  CELERY_BROKER_URL: cmVkaXM6Ly86ZGlmeWFpMTIzNDU2QHJlZGlzOjYzODAvMQ==
  WEAVIATE_API_KEY: V1ZGNVlUaGFIbGtZd2hHVVNtQ1Jnc1gzdEQ1bmdEOHBraWg=
  OCEANBASE_VECTOR_PASSWORD: ZGlmeWFpMTIzNDU2
  QDRANT_API_KEY: ZGlmeWFpMTIzNDU2
  COUCHBASE_PASSWORD: cGFzc3dvcmQ=
  PGVECTOR_PASSWORD: ZGlmeWFpMTIzNDU2
  VASTBASE_PASSWORD: RGlmeWFpMTIzNDU2
  ORACLE_PWD: RGlmeTEyMzQ1Ng==
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: UWF6d3N4ZWRjIUAjMTIz
  OPENGAUSS_PASSWORD: RGlmeUAxMjM=
  ELASTICSEARCH_PASSWORD: ZWxhc3RpYw==
  SANDBOX_API_KEY: ZGlmeS1zYW5kYm94
  PLUGIN_DAEMON_KEY: bFlraVlZVDZvd0crNzFvTGVyR3pBN0dYQ2dPVCsrN292YWV6V0FqcENqZitTamMzWnRVK3FVRWk=
  PLUGIN_DIFY_INNER_API_KEY: UWFoYlRlNzdDdHVYbXNmeWhSNyt2UmorL1hiVjFBYUZ5NjkxXHUwMDI2aStLRHYySnZ5MC9lQWg4WTE=
  INNER_API_KEY_FOR_PLUGIN: UWFoYlRlNzdDdHVYbXNmeWhSNyt2UmorL1hiVjFBYUZ5NjkxXHUwMDI2aStLRHYySnZ5MC9lQWg4WTE=
  JWT_SIGNING_KEY: c2stOWY3M3MzbGpUWFZjTVQzQmxiM2xqVHF0c0tpR0hYVmNNTDNCbGJrRkpMSzdV
